### ISSUE TITLE
Damage events showing up as generic

### ISSUE THREAD

**Issue by liftoff** [rtbo/rust-xcb#28]
When listening for damage events on the root window...

``` rust
let damage_id = conn.generate_id();
let report_level = damage::REPORT_LEVEL_RAW_RECTANGLES as u8; // Only report level that actually works!
let _ = damage::create(&conn, damage_id, root, report_level); // Watch for damage on the root window
```

The event returned by `let event = conn.wait_for_event().unwrap();` is always of type `xcb::Event<xcb::ffi::xcb_generic_event_t>` but I think it's supposed to be `xcb::Event<xcb_damage_notify_event_t>`.  Unless I'm missing some step that allows me to access the `drawable()` and `geometry()` methods?

**Comment by ibabushkin** [comment]
That's totally expected. You have `base::cast_event`, which you can use to cast to a specialized event type as soon as you know which type the event belongs to.

So you will probably want to `match` on `event.response_type()` and call `base::cast_event` on it, providing the right type.

**Comment by liftoff** [comment]
Ahh thanks!  For future googlers:

```rust
let event = conn.wait_for_event().unwrap();
println!("Event.response_type(): {:?}", event.response_type());
match event.response_type() {
    91 => { // Damage events are 91...  Not sure how to correctly reference this
        let e: &xcb::damage::NotifyEvent = xcb::base::cast_event(&event);
        println!("Drawable: {:?}", e.drawable());
        println!("x: {:?}, y: {:?}, width: {:?}, height: {:?}", e.area().x(), e.area().y(), e.area().width(), e.area().height());
    },
    _ => println!("Unknown event: {:?}", event.response_type()),
}
```

**Comment by rtbo** [comment]
No no no!
91 is not guaranteed to be correct every time. The following is valid for nearly all extensions you need to receive events from:

If you are interesting in receiving event `OPCODE` from an extension `ext`, what is needed is to initialize the extension, and fetch the first event (`first_event`) number of this extension.
Then when you receive an event with `response_type & !0x80 >= first_event`, you can check if it fits the event you are looking for : 
```rust
if event.response_type() & !0x80 == xcb::ext::OPCODE + first_event { 
    // handle ext::OPCODE
}
```
Examples of this process with `rust-xcb` for `xkb` extension are given in [examples/xkb_init.rs](https://github.com/rtbo/rust-xcb/blob/master/examples/xkb_init.rs) and in [toy_xcb](https://github.com/rtbo/toy_xcb).

In your case @liftoff , I guess that `damage` first event is 91 (this can vary from an X server installation to another) because `xcb::damage::NOTIFY == 0`. Each event has a symbolic constant attached.

**Comment by liftoff** [comment]
OK, here's a corrected version:

```rust

let damage_event = match conn.get_extension_data(damage::id()) {
    Some(r) => r.first_event(),
    None => { panic!("DAMAGE extension not supported by X server!"); }
};
println!("Damage Event ID: {:?}", damage_event); // Was 91 when I tested it
let event = conn.wait_for_event().unwrap();
match event.response_type() {
    damage_event => { // Use the correct event ID
        let e: &xcb::damage::NotifyEvent = xcb::base::cast_event(&event);
        println!("Drawable: {:?}", e.drawable());
        println!("x: {:?}, y: {:?}, width: {:?}, height: {:?}", e.area().x(), e.area().y(), e.area().width(), e.area().height());
    },
    _ => println!("Unknown event: {:?}", event.response_type()),
}
```

If it isn't already abundantly clear I have no idea what I'm doing =)
