### ISSUE TITLE
Calling `python3` isn't cross platform

### ISSUE THREAD

**Issue by clappski** [rtbo/rust-xcb#31]
Just had issues trying to build on my Arch Linux machine and received some cryptic errors about an unwrapped error with 'no such file or directory'. 

Will PR once fixed.

**Comment by sector-f** [comment]
Could you elaborate? I'm on Arch and I have a `python3` binary (owned by `python 3.6.0-2` according to `pacman -Qo`)

**Comment by c4eater** [comment]
Please reopen this bug. I have the same problem and it is not addressed in the upstream. The problem is that xcb compilation requires "python3" to be present in the system and issues the following error otherwise:

```
error: failed to run custom build command for `xcb v0.9.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installjKwNiV/release/build/xcb-5cfde8ee395df153/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find build dependency python3: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/c4eater/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.9.0/build.rs:75:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```



I reckon this as a bug. In a Python-less system, this dependency prevents building of **any** Rust crate implicitly or explicitly depending on xcb, eg. Alacritty.

Python is not guaranteed to be present in the system and the build systems should generally minimize invocation of third-party tools like Python. 

My proposal:
- As a quick fix: do a one-time run of rs_client.py and include the generated files in the code tree (I guess they aren't going to change too often) then exclude rs_client.py from the build process; leave rs_client.py in the tree; later, regenerate *.rs files manually via rs_client.py if there is a need. I can implement a PR with the said change if no one objects.

- In the long run: reimplement the code generator in Rust.



The CCR caption should say "not portable" instead of "not cross platform".

Thanks
Oleg

**Comment by Itsusinn** [comment]
I have the same problem, but the difference is that the error still occurs when cross-compiling even if I have python3 on the system.

The problem is reproduced on linux, but does not happen on mac-os.

(I think this may not be a problem caused by rust-xcb.)
