### ISSUE TITLE
ModuleNotFoundError: No module named 're'

### ISSUE THREAD

**Issue by yurivict** [rtbo/rust-xcb#89]
Encountered while building abstreet, see https://github.com/dabreegster/abstreet/issues/264

**Comment by Luro02** [comment]
When the crate is built the `rs_client.py` file is executed with `python3`:

https://github.com/rtbo/rust-xcb/blob/b44e52845e21621613d57bf5eb47c48c2ad521dd/build.rs#L68-L75

This issue seems to be, because your python3 environment is broken.

Could you try to run the following in the command line?


```
$ python3
>>> import re
```
(do not copy the `$` and `>>>`)
it should look something like this (if everything is working correctly):

```
lucas@luna:/media/hdd/home/projects/terminal_image$ python3
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>>
```

Maybe related: https://answers.ros.org/question/265455/modulenotfounderror-no-module-named-re/
